#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) [version]" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

name=$(IFS=.;set ${PWD##*/};echo $1)
version="$1"
[[ $# == 0 ]] && {
    version="$(date '+%Y.%-m.%-d')" || exit # date without zeroes
    url="https://pypi.org/pypi/"$name"/json"
    json="$(set -x; curl -fLs "$url")" && {
        version="$(echo "$json" | jq -r '.info.version')" || exit
    }
}
{ set -x; export SETUPPY_VERSION="$version"; }
{ set -x; export SETUPPY_CLASSIFIERS=""; }
#[ -e bin ] && {
#    scripts="$(find bin -type f)" || exit; export SETUP_SCRIPTS="$scripts";
#    export SETUP_SCRIPTS="$scripts"
#}
find . -name .DS_Store -o -name $'Icon\r' -exec rm {} \; || exit
( set -x; python3 -m setuppy > setup.py )

unset SETUPPY_CLASSIFIERS

description="$(cat .github/description.txt)" || exit
description="$(echo "$description" | sed -e 's/:[^()]*://g' | xargs)" # noemoji
user="$(git config user.name)" || exit

{ set -x; export SETUPPY_DESCRIPTION="$description"; { set +x; } 2>/dev/null; }
{ set -x; export SETUPPY_KEYWORDS="$keywords"; { set +x; } 2>/dev/null; } # todo: keywords
{ set -x; export SETUPPY_LICENSE="Unlicense"; { set +x; } 2>/dev/null; }
{ set -x; export SETUPPY_LONG_DESCRIPTION="file: README.md"; { set +x; } 2>/dev/null; }
{ set -x; export SETUPPY_LONG_DESCRIPTION_CONTENT_TYPE="text/markdown"; { set +x; } 2>/dev/null; }
{ set -x; export SETUPPY_URL="https://github.com/$user/${PWD##*/}"; { set +x; } 2>/dev/null; }

cat <<EOF > MANIFEST.in
exclude MANIFEST.in
exclude README.md
exclude requirements.txt
exclude setup-twine.py
EOF
( set -x; python3 -m setuppy sdist > setup-twine.py )
