#!/usr/bin/env bash
{ set +x; } 2>/dev/null

name=$(IFS=.;set ${PWD##*/};echo $1)
version="$(date '+%Y.%-m.%-d')" || exit # date without zeroes
url="https://pypi.org/pypi/"$name"/json"
json="$(set -x; curl -fLs "$url")" && {
    version="$(echo "$json" | jq -r '.info.version')" || exit
}

[ -e bin ] && {
    scripts="$(find bin -type f)" || exit; export SETUP_SCRIPTS="$scripts";
    export SETUP_SCRIPTS="$scripts"
}
( set -x; setup-prod "$name" "$version" > setup.py ) || exit
( set -x; cat setup.py )

cat <<EOF > MANIFEST.in
include requirements.txt
exclude MANIFEST.in
EOF
