#!/usr/bin/env bash
{ set +x; } 2>/dev/null

dist_dir="$(mktemp -d)" || exit

cd "$(set -x; repo:files:python:temp-copy)" || exit

( set -x; repo:files:python:clean ) || exit
( set -x; python3 setup.py bdist_wheel --dist-dir="$dist_dir" 1> /dev/null ) || exit
( set -x; repo:files:python:clean ) || exit
path="$( set -x; find "$dist_dir" -type f )" || exit
[[ -z "$path" ]] && echo "ERROR: $dist_dir EMPTY" 1>&2 && exit 1
echo "$path"
