#!/usr/bin/env bash
{ set +x; } 2>/dev/null

# https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/open.1.html

/usr/bin/open "$@"
exit
[[ $1 == "-a" ]] || [[ $1 == "-d" ]] && { /usr/bin/open "$@"; exit; }

while [[ $# != 0 ]]; do
  [[ $1 == . ]] && set -- "$PWD" "${@:2}"
  [[ $1 == "-R" ]] && { shift; /usr/bin/open -R "$@"; exit; }
  [ -d "$1" ] && { open:path "$1" || exit; shift; }
  [[ "$1" == *.aiff ]] && { /usr/bin/open "$1" || exit; shift; }
  [[ "$1" == *.app ]] || [[ "$1" == *.app/ ]] && { /usr/bin/open "$1" || exit; shift; }
  [[ "$1" == *.command ]] && { open:command "$1" || exit; shift; }
  [[ "$1" == *.mp3 ]] && { open:mp3 "$1" || exit; shift; continue; }
  [[ $1 == *"://"* ]] && { open:url "$1" || exit; shift; }
  [ -e "$1" ] && [[ $1 == ~/Movies/* ]] && { open:video "$1"; exit; }
  [[ $# != 0 ]] && { /usr/bin/open "$@"; exit; };:
done
[[ $# != 0 ]] && { /usr/bin/open "$@" || exit; };:
