#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path ..."
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# == 0 ]] && usage

while (($#)); do
    ! [ -e "$1" ] && echo "ERROR: '$1' NOT EXISTS" 1>&2 && exit 1
    ! [ -f "$1" ] && echo "ERROR: '$1' NOT A FILE" 1>&2 && exit 1
    ! [ -s "$1" ] && echo "ERROR: '$1' EMPTY" 1>&2 && exit 1
    shift
done;:
