#!/usr/bin/env bash
{ set +x; } 2>/dev/null

! [ -e setup.py ] && exit

export README_BASENAME="${PWD##*/}"

cat <<"EOF" | envsubst;:
[![](https://github.com/andrewp-as-is/${README_BASENAME}/workflows/tests42/badge.svg)](https://github.com/andrewp-as-is/${README_BASENAME}/actions)
EOF
