#!/usr/bin/env bash
{ set +x; } 2>/dev/null

# MAJOR.MINOR.PATCH, http://semver.org/

# 1) init version
# 2) generate requirements.txt
# 3) generate setup.cfg
# 4) bump version if package changed
# 5) generate package.json, setup.cfg again

! [ -e setup.py ] && echo "SKIP ($PWD): setup.py NOT EXISTS" && exit

#name="$(grep ^"name = " setup.cfg | awk -F" = " '{print $2}')"
#v="$(grep ^"version = " setup.cfg | awk -F" = " '{print $2}')"
name="$(python3 setup.py --name)" || exit
version="$(date '+%Y.%-m.%-d')" || exit # date without zeroes
url="https://pypi.org/pypi/"$name"/json"

v="$(python3 setup.py --version)" || exit
json="$(set -x; curl -fLs "$url")" || exit
pv="$(echo "$json" | jq -r '.info.version')" || exit

[[ -z "$v" ]] && echo "ERROR: version unknown" && exit 1
[[ -z "$pv" ]] && echo "SKIP: https://pypi.org/project/$name/ NOT REGISTERED" && exit

[[ $v != $pv ]] && {
    echo $v$'\n'$pv | sort -V | tail -1 | grep -q "$v" && echo "SKIP: $v > $pv" && exit
}

( set -x; bash -l ~/.repo-scripts/files/python/requirements.txt/create.sh ) || exit
( set -x; bash -l ~/.repo-scripts/files/python/classifiers.txt/create.sh ) || exit
( set -x; bash -l ~/.repo-scripts/files/python/setup.py/create.sh ) || exit

temp_python="$(set -x; bash -l ~/.repo-scripts/python/temp-copy.sh)" || exit
diff="$(
    cd "$temp_python" || exit
    ( set -x; python3 -m setupcfg.metadata.version "$pv") || exit
    dist_dir="$(mktemp -d)" || exit
    ( set -x; python3 setup.py sdist --dist-dir="$dist_dir" 1> /dev/null ) || exit
    sdist="$(find "$dist_dir" -type f -name "*.tar.gz")" || exit
    url="$(python3 -m pypi_get.urls "$name" | grep tar.gz)"
    tar-diff "$sdist" "$url"
)" || exit
[[ -z "$diff" ]] && echo "SKIP: uptodate" && exit
echo "$diff"

( set -x; setup-prod "$name" "$version" > setup.py ) || exit
( set -x; cat setup.py )
# todo: node
