#!/usr/bin/env bash
{ set +x; } 2>/dev/null

! [ -e setup.py ] && echo "SKIP: setup.py NOT EXISTS" && exit

set -- ".config/description.txt"
[[ $PWD == *.py ]] || [ -d scripts ] && set -- "$@" setup.py
[ -e setup.py ] && {
    ! [ -e requirements.txt ] && echo "ERROR: requirements.txt NOT EXISTS" 1>&2 && exit 1
    set -- "$@" ".config/keywords.txt" "README.md"
}
[ -d "setup.py" ] && set -- "$@" ".config/cache/pypi.org/README.md"
[ -d "package.json" ] && set -- "$@" ".config/cache/npmjs.com/README.md"
[[ $# != 0 ]] && { ( set -x; file-not-empty "$@" ) || exit; };:
