#!/usr/bin/env bash
{ set +x; } 2>/dev/null

[[ "$PWD" != */git/* ]] && echo "ERROR: $PWD" 1>&2 && exit 1
[[ "$PWD" == */gists/* ]] && {
    ! [ -s description.txt ] && { echo "${PWD##*/}" > description.txt || exit; }
    echo "SKIP: $PWD"; exit
}

XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME-$HOME/.local/share}"

! [ -e .readme ] && { ( set -x; mkdir .readme ) || exit; }
cat <<EOF > .readme/_create.sh
#!/usr/bin/env bash
{ set +x; } 2>/dev/null

( set -x; repo-readme )
EOF
cat <<EOF > .readme/_pbcopy.sh
#!/usr/bin/env bash
{ set +x; } 2>/dev/null

( set -x; cat README.md | pbcopy )
( set -x; cat README.md )
EOF

[[ "${PWD##*/}" == *.py ]] || [[ "${PWD##*/}" == *-cli ]] || [ -e bin ] && {
    ! [ -e tests ] && { mkdir tests || exit; }
}

set -- .github/description.txt
[ -e tests ] && [[ $PWD != */dotfiles ]] && {
    set -- "$@" .readme/examples.md .readme/features.md
}

( set -x; mktouch "$@" ) || exit

XDG_CONFIG_HOME="${XDG_CONFIG_HOME-$HOME/.config}"
REPO_CONFIG="${REPO_CONFIG-$XDG_CONFIG_HOME/repo-config}"

[ -e tests ] && [[ $PWD != */dotfiles ]] && {
    ! [ -e .github/workflows ] && { ( set -x; mkdir -p .github/workflows ) || exit; }

    cat <<EOF > .github/workflows/tests42.yml || exit
name: tests42
on: [push, pull_request]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: andrewp-as-is/python-tests42-action@master
EOF
unlicense-text > UNLICENSE || exit
};:
[ -e package.json ] && {
    cat <<EOF > .npmignore
# ~/.npmignore NOT SUPPORTED :(

.*
/build
/.config
/dist
/examples
/Icon
/Icon?
/MANIFEST
/MANIFEST.in
/setup.cfg
/tests
.DS_Store
*.egg-info
*.md
*.py
*.pyc
*.txt
*.yml
UNLICENSE
EOF
};:
