#!/usr/bin/env bash
{ set +x; } 2>/dev/null


usage() {
    echo "usage: $(basename $0) path" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 1 ]] && usage

[[ $1 == */.config/* ]] && {
    repo="$(echo $1 | awk -F '/.config' '{print $1}')"
    repo-config save "$repo" || exit
}
:
