#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path ssh_host" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 2 ]] && usage

tmp="$(ssh "$2" mktemp -d)" || exit

rsync -a --delete "$1" "$2":"$tmp" || exit
echo $tmp
