#!/usr/bin/env bash
{ set +x; } 2>/dev/null

[[ "$PWD" != */gists/* ]] && { ( set -x; bash -l ~/.repo-scripts/git/init.sh ) || exit; }
( set -x; bash -l ~/.repo-scripts/git/commit.sh ) || exit

[[ "$PWD" != */gists/* ]] && {
     ( set -x; bash -l ~/.repo-scripts/git/remote/add.sh ) || exit
}
( set -x; bash -l ~/.repo-scripts/web/github.com/create.sh ) || exit
( set -x; bash -l ~/.repo-scripts/web/github.com/push.sh ) || exit

( set -x; bash -l ~/.repo-scripts/web/github.com/description/update.sh ) || exit
[[ "$PWD" != */gists/* ]] && {
    ( set -x; bash -l ~/.repo-scripts/web/github.com/homepage/update.sh ) || exit
    ( set -x; bash -l ~/.repo-scripts/web/github.com/topics/create.sh ) || exit
    ( set -x; bash -l ~/.repo-scripts/web/github.com/topics/update.sh ) || exit
    ( set -x; bash -l ~/.repo-scripts/web/github.com/webhooks/add.sh ) || exit
}
echo
