#!/usr/bin/env bash
{ set +x; } 2>/dev/null

[[ "$PWD" == */gists/* ]] && echo "SKIP ($PWD)" && exit

fullname="$(repo-github-fullname)" || exit
username="$(IFS='/';set $fullname; echo $1)"

url="https://github.com/$fullname"

# homepage="https://github42.com/$fullname/"
homepage="https://github42.com/$username/"
[ -e .config/homepage.txt ] && { homepage="$(cat .config/homepage.txt)" || exit; }

( set -x; curl -f -I -s -o /dev/null "$url" ) || { echo "SKIP: $url NOT EXISTS"; exit; }

( set -x; github-homepage "$fullname" "$homepage" ) || exit
