#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# != 1 ]] && usage

shopt -s nocasematch
[[ $PWD == *sqlite* ]] && {
    db="$(mktemp)" || exit
    sqlite3 "$db" < "$1"
}
[[ $PWD == *postgres* ]] && {
    dbname="$(mktempdb)" || exit
    createdb "$dbname" 2> /dev/null
    psql -f "$1" "$dbname"; exit
 }

echo "ERROR ($1): unknown sql engine" 1>&2 && exit 1
