#!/usr/bin/env bash
{ set +x; } 2>/dev/null

usage() {
    echo "usage: $(basename $0) path" 1>&2
    [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; exit
}

[[ $1 == "-h" ]] || [[ $1 == "--help" ]] && usage "$@"

[[ $# == 0 ]] && usage

! [ -e "$1" ] && echo "ERROR: $1 NOT EXISTS" && exit 1

SSH_HOSTNAME=aws
PGDATABASE="$(django-database-url-dbname)" || exit
PGPORT="$(django-database-url-port)" || exit
PGUSER="$(django-database-url-user)" || exit
DEST="$(set -x; ssh "${SSH_HOSTNAME}" mktemp -d)" || exit

( set -x; rsync -a --delete "$1" "${SSH_HOSTNAME}":"${DEST}" ) || exit
( set -x; ssh "${SSH_HOSTNAME}" "find ${DEST} -name '*.sql' ! -name '_*' -exec sh -c 'set -x; psql -U ${PGUSER} -p ${PGPORT} -f \$0 ${PGDATABASE}' {} \;" )
